name: private-release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out ${{ github.ref }}
        uses: actions/checkout@v2

      - run: npm cache clean --force

      - run: npx version-from-git --no-git-tag-version

      - run: npm ci --no-production

      - name: Propagate versions
        run: node_modules/.bin/lerna version --exact --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq --unbuffered -r .version`

      - run: npm run bootstrap

      - run: npm run build
        env:
          NODE_ENV: production

      # ======--
      # (Setup Node) >>
      #
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: https://npm.pkg.github.com/
          scope: '@${{ github.repository_owner }}'

      # ======--
      # (API) >>
      #
      - name: (API) >> Set name and env variables
        run: |
          cd packages/api
          echo "package_name=@${{ github.repository_owner }}/$(cat package.json | jq --unbuffered -r '.name')" >> $GITHUB_ENV
          echo "package_registry=https://npm.pkg.github.com/@${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "package_repo_url=git://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "package_bugs_url=https://github.com/${{ github.repository }}/issues" >> $GITHUB_ENV
          echo "package_homepage_url=https://github.com/${{ github.repository }}/tree/main/packages/component#readme" >> $GITHUB_ENV

      - name: (API) >> Modify package.json
        run: |
          cd packages/api
          jq --unbuffered --indent 2 --arg package_name "${{ env.package_name }}" --arg package_access "restricted" --arg package_registry "${{ env.package_registry }}" --arg package_repo_url "${{ env.package_repo_url }}" --arg package_bugs_url "${{ env.package_bugs_url }}" --arg package_homepage_url "${{ env.package_homepage_url }}".name = $package_name | .publishConfig.access = $package_access | .publishConfig.registry = $package_registry | .repository.url = $package_repo_url | .bugs.url = $package_bugs_url | .homepage = $package_homepage_url | .dependencies |= with_entries( if ( .key | contains("botframework-") and ( contains("directlinejs" ) | not )) then .key |= $package_scope + . else . end)' package.json > temp.json && mv temp.json package.json

      - name: (API) >> Publish
        run: |
          cd packages/api
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PORTER_SHARED_PAT }}

      # ======--
      # (BUNDLE) >>
      #
      - name: (Bundle) >> Set name and env variables
        run: |
          cd packages/bundle
          echo "package_name=@${{ github.repository_owner }}/$(cat package.json | jq --unbuffered -r '.name')" >> $GITHUB_ENV
          echo "package_registry=https://npm.pkg.github.com/@${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "package_repo_url=git://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "package_bugs_url=https://github.com/${{ github.repository }}/issues" >> $GITHUB_ENV
          echo "package_homepage_url=https://github.com/${{ github.repository }}/tree/main/packages/component#readme" >> $GITHUB_ENV

      - name: (Bundle) >> Modify package.json
        run: |
          cd packages/bundle
          jq --unbuffered --indent 2 --arg package_name "${{ env.package_name }}" --arg package_access "restricted" --arg package_registry "${{ env.package_registry }}" --arg package_repo_url "${{ env.package_repo_url }}" --arg package_bugs_url "${{ env.package_bugs_url }}" --arg package_homepage_url "${{ env.package_homepage_url }}".name = $package_name | .publishConfig.access = $package_access | .publishConfig.registry = $package_registry | .repository.url = $package_repo_url | .bugs.url = $package_bugs_url | .homepage = $package_homepage_url | .dependencies |= with_entries( if ( .key | contains("botframework-") and ( contains("directlinejs" ) | not )) then .key |= $package_scope + . else . end)' package.json > temp.json && mv temp.json package.json

      - name: (Bundle) >> Publish
        run: |
          cd packages/bundle
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PORTER_SHARED_PAT }}

      # ======--
      # (COMPONENT) >>
      #
      - name: (Component) >> Set name and env variables
        run: |
          cd packages/component
          echo "package_name=@${{ github.repository_owner }}/$(cat package.json | jq --unbuffered -r '.name')" >> $GITHUB_ENV
          echo "package_registry=https://npm.pkg.github.com/@${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "package_repo_url=git://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "package_bugs_url=https://github.com/${{ github.repository }}/issues" >> $GITHUB_ENV
          echo "package_homepage_url=https://github.com/${{ github.repository }}/tree/main/packages/component#readme" >> $GITHUB_ENV

      - name: (Component) >> Modify package.json
        run: |
          cd packages/component
          jq --unbuffered --indent 2 --arg package_name "${{ env.package_name }}" --arg package_access "restricted" --arg package_registry "${{ env.package_registry }}" --arg package_repo_url "${{ env.package_repo_url }}" --arg package_bugs_url "${{ env.package_bugs_url }}" --arg package_homepage_url "${{ env.package_homepage_url }}".name = $package_name | .publishConfig.access = $package_access | .publishConfig.registry = $package_registry | .repository.url = $package_repo_url | .bugs.url = $package_bugs_url | .homepage = $package_homepage_url | .dependencies |= with_entries( if ( .key | contains("botframework-") and ( contains("directlinejs" ) | not )) then .key |= $package_scope + . else . end)' package.json > temp.json && mv temp.json package.json

      - name: (Component) >> Publish
        run: |
          cd packages/component
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PORTER_SHARED_PAT }}

      # ======--
      # (CORE) >>
      #
      - name: (Core) >> Set name and env variables
        run: |
          cd packages/core
          echo "package_name=@${{ github.repository_owner }}/$(cat package.json | jq --unbuffered -r '.name')" >> $GITHUB_ENV
          echo "package_registry=https://npm.pkg.github.com/@${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "package_repo_url=git://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "package_bugs_url=https://github.com/${{ github.repository }}/issues" >> $GITHUB_ENV
          echo "package_homepage_url=https://github.com/${{ github.repository }}/tree/main/packages/component#readme" >> $GITHUB_ENV

      - name: (Core) >> Modify package.json
        run: |
          cd packages/core
          jq --unbuffered --indent 2 --arg package_name "${{ env.package_name }}" --arg package_access "restricted" --arg package_registry "${{ env.package_registry }}" --arg package_repo_url "${{ env.package_repo_url }}" --arg package_bugs_url "${{ env.package_bugs_url }}" --arg package_homepage_url "${{ env.package_homepage_url }}".name = $package_name | .publishConfig.access = $package_access | .publishConfig.registry = $package_registry | .repository.url = $package_repo_url | .bugs.url = $package_bugs_url | .homepage = $package_homepage_url | .dependencies |= with_entries( if ( .key | contains("botframework-") and ( contains("directlinejs" ) | not )) then .key |= $package_scope + . else . end)' package.json > temp.json && mv temp.json package.json

      - name: (Core) >> Publish
        run: |
          cd packages/core
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PORTER_SHARED_PAT }}

      # ======--
      # (DLSPEECH) >>
      #
      - name: (DLSpeech) >> Set name and env variables
        run: |
          cd packages/directlinespeech
          echo "package_name=@${{ github.repository_owner }}/$(cat package.json | jq --unbuffered -r '.name')" >> $GITHUB_ENV
          echo "package_registry=https://npm.pkg.github.com/@${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "package_repo_url=git://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          echo "package_bugs_url=https://github.com/${{ github.repository }}/issues" >> $GITHUB_ENV
          echo "package_homepage_url=https://github.com/${{ github.repository }}/tree/main/packages/component#readme" >> $GITHUB_ENV

      - name: (DLSpeech) >> Modify package.json
        run: |
          cd packages/directlinespeech
          jq --unbuffered --indent 2 --arg package_name "${{ env.package_name }}" --arg package_access "restricted" --arg package_registry "${{ env.package_registry }}" --arg package_repo_url "${{ env.package_repo_url }}" --arg package_bugs_url "${{ env.package_bugs_url }}" --arg package_homepage_url "${{ env.package_homepage_url }}".name = $package_name | .publishConfig.access = $package_access | .publishConfig.registry = $package_registry | .repository.url = $package_repo_url | .bugs.url = $package_bugs_url | .homepage = $package_homepage_url | .dependencies |= with_entries( if ( .key | contains("botframework-") and ( contains("directlinejs" ) | not )) then .key |= $package_scope + . else . end)' package.json > temp.json && mv temp.json package.json
      - name: (DLSpeech) >> Publish
        run: |
          cd packages/directlinespeech
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.PORTER_SHARED_PAT }}

